server:
  port: 9022
  address: 127.0.0.1

spring:
  datasource:
  url: jdbc:postgresql://localhost:5050/Invitations?currentSchema=invites
  username: postgres
  password: admin
  driver-class-name: org.postgresql.Driver
