server:
  port: 9022

spring:
  application:
    name: guest-service
  datasource:
    url: jdbc:postgresql://localhost:5432/Invitations
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    # properties:
    #   hibernate:
    #     dialect: org.hibernate.dialect.PostgreSQLDialect
        
